export const NAVIGATION_PUSH = "NAVIGATION_PUSH";
export const NAVIGATION_POP = "NAVIGATION_POP";
export const NAVIGATION_START = "NAVIGATION_START";
export const NAVIGATION_RESET = "NAVIGATION_RESET";